language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lcpunch/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lcpunch/docker-react npm run test